### ISSUE TITLE
Elastic constraint calculation bug

### ISSUE THREAD

**Issue by JeckleCed** [soufianekhiat/N-Pendulum#1]
It seems like elastic constraint computation contains a bug:
```
f32 const fCoefA = fMassA/( fMassA + fMassB );
f32 const fCoefB = fMassB/( fMassA + fMassB );
vA = vA + vDir*fDelta*fCoefA*0.5f;
vB = vB - vDir*fDelta*fCoefB*0.5f;
```
(fCoefA + fCoefB) should already add up to 1.0, so the 0.5f are unnecessary as they will make the constraint too elastic
Correct code should be :
```
vA = vA + vDir*fDelta*fCoefA;
vB = vB - vDir*fDelta*fCoefB;
```

**Comment by soufianekhiat** [comment]
Fix with:
https://github.com/soufianekhiat/N-Pendulum/commit/a5e10665b38565fa64e6c6337d66f1a350c2da23
